function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-Jun-2021 12:50:14

% Create figure
figure('Color',[1 1 1],'OuterPosition',[481 325.4 574.4 509.6]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1,'Marker','o','LineWidth',2,'Color',[1 0 0]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,5,30.1565898155018);
% Create datatip
datatip(plot1,'DataIndex',31,'Location','southeast');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,0,26.7363897170134);
% Create datatip
datatip(plot1,'DataIndex',26,'Location','northwest');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,10,33.1330184043793);
% Create datatip
datatip(plot1,'DataIndex',36);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,-10,13.4751239175754);
% Create datatip
datatip(plot1,'DataIndex',16,'Location','northwest');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,-15,7.06110209157653);
% Create datatip
datatip(plot1,'DataIndex',11,'Location','northwest');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,-5,20.151196702478);
% Create datatip
datatip(plot1,'DataIndex',21,'Location','northwest');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,-20,2.29098409742552);
% Create datatip
datatip(plot1,'DataIndex',6,'Location','northwest');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,15,14.4267776869159);
% Create datatip
datatip(plot1,'DataIndex',41);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,20,5.4635146957029);
% Create datatip
datatip(plot1,'DataIndex',46);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,25,0.982654115853082);
% Create datatip
datatip(plot1,'DataIndex',51,'Location','northwest');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,30,0.0820008341901183);
% Create datatip
datatip(plot1,'DataIndex',56,'Location','northeast');

% Create ylabel
ylabel({'conv eff (\eta)'});

% Create xlabel
xlabel({'pin(dBm)'});

box(axes1,'on');
grid(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',20);
