function [fitresult, gof] = createFit1(I_diode, V_diode)
%CREATEFIT1(I_DIODE,V_DIODE)
%  Create a fit.
%
%  Data for 'VI chara SMS7630 cubic spline' fit:
%      X Input : I_diode
%      Y Output: V_diode
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Apr-2021 13:08:19


%% Fit: 'VI chara SMS7630 cubic spline'.
[xData, yData] = prepareCurveData( I_diode, V_diode );

% Set up fittype and options.
ft = 'splineinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
% figure( 'Name', 'VI chara SMS7630 cubic spline' );
% h = plot( fitresult, xData, yData );
% legend( h, 'V_diode vs. I_diode', 'VI chara SMS7630 cubic spline', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'I_diode', 'Interpreter', 'none' );
% ylabel( 'V_diode', 'Interpreter', 'none' );
% grid on


