% Initialise MATLAB
clc; close all;

% Reading the msh structure generated by executing the GMSH generated .m file
nodeList = msh.POS;
elementList = msh.HEXAS(:,1:8);

save nodeList.txt nodeList -ascii
save elementList.txt elementList -ascii