function V = LTSpiceCall_2(I1,I2,vol,delt)
%% USEFUL PATHS

% C:\Users\athul\OneDrive - Indian Institute of
% Science\Dev\MATLAB_Code\MATLAB_FDTD_SPICE\Diode_ckt.net

% "C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe"

%% CODE

netlist_1 = ['C:\Users\MWLAB\OneDrive - Indian Institute of Science\Desktop\LTSpiceCkts\voltage_source\voltage_source.net'];
code_1 = ['* C:\\Users\\MWLAB\\OneDrive - Indian Institute of Science\\Desktop\\LTSpiceCkts\\voltage_source\\voltage_source.asc\r\n'...
'V1 N001 0 {V}\r\n'...
'R1 N001 0 250k\r\n'...
'C1 N001 0 62.332f\r\n'...
'I1 0 N001 {I}\r\n'...
'.param I=',num2str(I1),' V=',num2str(vol),'\r\n'...
'.tran ', num2str(delt),'\r\n'...
'.backanno\r\n'...
'.end\r\n'];

% code  = ['* C:\\Users\\MWLAB\\OneDrive - Indian Institute of Science\\Desktop\\LTSpiceCkts\\RC_circuit\\RC_circuit.asc\r\n'...
% 'I1 0 N001 {CURRENT_VALUE}\r\n'...
% 'C1 N001 0 31.166e-15\r\n'...
% 'R1 N002 N001 25\r\n'...
% 'R2 N002 0 25\r\n'...
% '.params CURRENT_VALUE=',num2str(current_val),'\r\n'...
% '.tran 1ns\r\n'...
% '.backanno\r\n'...
% '.end\r\n'];
% 

% writing netlist to a file
fid = fopen(netlist_1,'w+');
fprintf(fid,code_1);
fid = fclose(fid);

dos('LTSpiceCall_1.bat');
% pause(0.1);
dos('LTSpiceEnd.bat');

raw_data = LTspice2Matlab('C:\Users\MWLAB\OneDrive - Indian Institute of Science\Desktop\LTSpiceCkts\voltage_source\voltage_source.raw');
V1 = mean(raw_data.variable_mat(1,:));

netlist_2 = ['C:\Users\MWLAB\OneDrive - Indian Institute of Science\Desktop\LTSpiceCkts\voltage_source\resistor.net'];
code_2 = ['* C:\\Users\\MWLAB\\OneDrive - Indian Institute of Science\\Desktop\\LTSpiceCkts\\voltage_source\\resistor.asc\r\n'...
'C1 N001 0 62.332f\r\n'...
'I1 0 N001 {I}\r\n'...
'R1 N001 0 100\r\n'...
'.param I=',num2str(I2),'\r\n'...
'.tran ', num2str(delt),'\r\n'...
'.backanno\r\n'...
'.end\r\n'];

fid = fopen(netlist_2,'w+');
fprintf(fid,code_2);
fid = fclose(fid);

dos('LTSpiceCall_2.bat');
% pause(0.1);
dos('LTSpiceEnd.bat');

raw_data = LTspice2Matlab('C:\Users\MWLAB\OneDrive - Indian Institute of Science\Desktop\LTSpiceCkts\voltage_source\resistor.raw');
V2 = mean(raw_data.variable_mat(4,:))*250e3;
V = [V1;V2];
end