function raw_data = LTSpiceCall
%% USEFUL PATHS

% C:\Users\athul\OneDrive - Indian Institute of
% Science\Dev\MATLAB_Code\MATLAB_FDTD_SPICE\Diode_ckt.net

% "C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe"

%% CODE

netlist = ['C:\LTspiceXVII\Draft6.net'];
code = ['* C:\\LTspiceXVII\\Draft6.asc\r\n'...
'V1 N001 0 SINE(0 1 2e9 0 0 90)\r\n'...
'R1 N002 N001 50\r\n'...
'R2 0 N003 500\r\n'...
'D1 N002 N003 MyDiode\r\n'...
'C1 N003 0 100n\r\n'...
'.tran 100e-12\r\n'...
'.model MyDiode D(Is=5u Rs=20 N=1.05 tt=1e-11 Cjo=0.14p Vj=0.34 M=0.4 Fc=0.5 Bv=2 Eg=0.69)\r\n'...
'.backanno\r\n'...
'.end\r\n'];
% code  = ['* C:\\Users\\MWLAB\\OneDrive - Indian Institute of Science\\Desktop\\LTSpiceCkts\\RC_circuit\\RC_circuit.asc\r\n'...
% 'I1 0 N001 {CURRENT_VALUE}\r\n'...
% 'C1 N001 0 31.166e-15\r\n'...
% 'R1 N002 N001 25\r\n'...
% 'R2 N002 0 25\r\n'...
% '.params CURRENT_VALUE=',num2str(current_val),'\r\n'...
% '.tran 1ns\r\n'...
% '.backanno\r\n'...
% '.end\r\n'];
% 

% writing netlist to a file
fid = fopen(netlist,'w+');
fprintf(fid,code);
fclose(fid);

dos('LTSpiceCall.bat');
pause(0.5);
dos('LTSpiceEnd.bat');
raw_data = LTspice2Matlab('C:\LTspiceXVII\Draft6.raw');
end

