function Startup_Program
load('TD3DRad_DATA.mat')
S=1;
T=10000/S;
fmax=5.2e9;
CN_FDTD_Solver(T, ...
    fmax,...
    nxtot,...
    nytot,...
    nztot,...
    t0, ...
    tau, ...
    delt, ...
    pml_thickness, ...
    krEx, ...
    krEy, ...
    krEz, ...
    krHx, ...
    krHy, ...
    krHz, ...
    Exincamp, ...
    Eyincamp, ...
    Ezincamp, ...
    Hxincamp, ...
    Hyincamp, ...
    Hzincamp, ...
    Exincident_current, ...
    Eyincident_current, ...
    Ezincident_current, ...
    Hxincident_current, ...
    Hyincident_current, ...
    Hzincident_current, ...
    Exincident_past, ...
    Eyincident_past, ...
    Ezincident_past, ...
    Hxincident_past, ...
    Hyincident_past, ...
    Hzincident_past, delx,dely,delz,S,...
    CHx_current, CHy_current, CHz_current, ...
    CHx_past, CHy_past, CHz_past, ...
    CEx_current, CEy_current, CEz_current, ...
    CEx_past, CEy_past, CEz_past, sigma_x,sigma_y,sigma_z,eps_x,eps_y,eps_z)


end