clc;close all;clear;
load('D:\OneDrive - Indian Institute of Science\Dev\MATLAB_Code\MATLAB_Code-master\new_codes\02Oct2021\case13.mat');
LL=length(nffieldyy);
NN=1e6;
VC1=[VC1 zeros(1,NN)];
nffieldyy=[nffieldyy zeros(1,NN)];
fffieldyy=[fffieldyy zeros(1,NN)];
LL=length(nffieldyy);
FFT_NFFIELDYY=fftshift(fft(nffieldyy))/LL;
FFT_FFFIELDYY=fftshift(fft(fffieldyy))/LL;
FFT_VC1=fftshift(fft(VC1))/LL;
FF=(1/delt)*(-LL/2:LL/2-1)/LL;
figure(1),plot(FF,abs(FFT_NFFIELDYY));grid on;hold on;plot(FF,abs(FFT_FFFIELDYY));hold on;grid on;xlim([-1e10,1e10]);
xlabel('freq(Hz)');ylabel('FFT');legend('FFT of nearfield Ey','FFT of farfield Ey');
figure(2),plot(FF,abs(FFT_VC1));hold on;grid on;xlim([-1e10,1e10]);hold on;grid on;
xlabel('freq(Hz)');ylabel('FFT');legend('FFT of antenna terminal voltage');
log10_nffieldyy=log10(abs(nffieldyy));
log10_fffieldyy=log10(abs(fffieldyy));
log10_VC1=log10(abs(VC1));
figure(3),plot(log10_VC1);hold on;grid on;plot(log10_nffieldyy);hold on;grid on;plot(log10_fffieldyy);
xlabel('time steps');ylabel('log10|amplitude|');legend('log10 antenna terminal voltage','log10 nearfield Ey','log10 farfield Ey');
figure(4),plot(VC1);hold on;grid on;plot(nffieldyy);hold on;grid on;plot(fffieldyy);xlim([1,6000]);
xlabel('time steps');ylabel('amplitude');legend('antenna terminal voltage','nearfield Ey','farfield Ey');